/**
 * api/models/Team.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Pre-populated by admin — contains shortlisted teams.
 * Team codes are generated by admin and are IMMUTABLE once set.
 * Members are added by the team leader during registration (payment flow).
 * ─────────────────────────────────────────────────────────────────────────────
 */

import mongoose from 'mongoose';

const MemberSchema = new mongoose.Schema({
  name:  { type: String, required: true, trim: true },
  email: { type: String, required: true, trim: true, lowercase: true },
  phone: { type: String, required: true, trim: true },
}, { _id: false });

const TeamSchema = new mongoose.Schema(
  {
    // ── Unique Code (set by admin, IMMUTABLE once set) ────────────────────
    code: {
      type:      String,
      default:   null,
      uppercase: true,
      trim:      true,
    },

    // Once true, code cannot be changed — enforced at API level
    codeGenerated: { type: Boolean, default: false },

    // ── Team Details (imported from Excel, editable until code is generated) ─
    teamName:    { type: String, required: true, trim: true },
    collegeName: { type: String, required: true, trim: true },
    branch:      { type: String, required: true, trim: true },
    memberCount: { type: Number, required: true, min: 1, max: 4, default: 1 },

    // ── Leader (auto-filled on register page, locked) ─────────────────────
    leader: {
      name:  { type: String, required: true, trim: true },
      email: { type: String, required: true, trim: true, lowercase: true },
      phone: { type: String, required: true, trim: true },
    },

    // ── Team Members (added by leader during registration) ────────────────
    members: { type: [MemberSchema], default: [] },

    // ── Add-ons ───────────────────────────────────────────────────────────
    mentorSession: { type: Boolean, default: false },
    totalAmount:   { type: Number, default: 800 },  // ₹800 or ₹1100

    // ── Payment ───────────────────────────────────────────────────────────
    confirmationEmailSent: { type: Boolean, default: false },
    paymentReminderSent: { type: Boolean, default: false },
    paymentStatus: {
      type:    String,
      enum:    ['pending', 'paid', 'failed'],
      default: 'pending',
    },
    paymentDate:        { type: Date,   default: null },
    paymentScreenshotUrl: { type: String, default: null },
    cashfreeOrderId:    { type: String, default: null },
    cashfreePaymentId:  { type: String, default: null },

    // ── PS Drop ───────────────────────────────────────────────────────────
    psSelectionId: {
      type:    mongoose.Schema.Types.ObjectId,
      ref:     'ProblemStatement',
      default: null,
    },
    psSelectedAt: { type: Date, default: null },
    
    // ── Mentorship ────────────────────────────────────────────────────────
    mentor: {
      name:     { type: String, default: null },
      contact:  { type: String, default: null },
      linkedin: { type: String, default: null },
    },

    // ── Mentorship Workflow ───────────────────────────────────────────────
    mentorshipStatus: { 
      type: String, 
      enum: ['not_requested', 'pending', 'approved'], 
      default: 'not_requested' 
    },
    mentorshipReceiptUrl: { type: String, default: null },
  },
  {
    timestamps: true,
    collection: 'teams',
  }
);

// Indexes
TeamSchema.index({ paymentStatus: 1 });
TeamSchema.index({ codeGenerated: 1 });
TeamSchema.index({ 'leader.email': 1 });
TeamSchema.index({ psSelectionId: 1 }, { sparse: true });
TeamSchema.index({ paymentStatus: 1, psSelectionId: 1 });

export const Team =
  mongoose.models.Team || mongoose.model('Team', TeamSchema);
